# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    EnumDescriptor as google___protobuf___descriptor___EnumDescriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)

from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
    RepeatedScalarFieldContainer as google___protobuf___internal___containers___RepeatedScalarFieldContainer,
)

from google.protobuf.internal.enum_type_wrapper import (
    _EnumTypeWrapper as google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Iterable as typing___Iterable,
    NewType as typing___NewType,
    Optional as typing___Optional,
    Text as typing___Text,
    cast as typing___cast,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int


DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

ChannelTypeValue = typing___NewType('ChannelTypeValue', builtin___int)
type___ChannelTypeValue = ChannelTypeValue
ChannelType: _ChannelType
class _ChannelType(google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper[ChannelTypeValue]):
    DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
    MICROPHONE = typing___cast(ChannelTypeValue, 0)
    BAROMETER = typing___cast(ChannelTypeValue, 1)
    LATITUDE = typing___cast(ChannelTypeValue, 2)
    LONGITUDE = typing___cast(ChannelTypeValue, 3)
    SPEED = typing___cast(ChannelTypeValue, 4)
    ALTITUDE = typing___cast(ChannelTypeValue, 5)
    RESERVED_0 = typing___cast(ChannelTypeValue, 6)
    RESERVED_1 = typing___cast(ChannelTypeValue, 7)
    RESERVED_2 = typing___cast(ChannelTypeValue, 8)
    TIME_SYNCHRONIZATION = typing___cast(ChannelTypeValue, 9)
    ACCURACY = typing___cast(ChannelTypeValue, 10)
    ACCELEROMETER_X = typing___cast(ChannelTypeValue, 11)
    ACCELEROMETER_Y = typing___cast(ChannelTypeValue, 12)
    ACCELEROMETER_Z = typing___cast(ChannelTypeValue, 13)
    MAGNETOMETER_X = typing___cast(ChannelTypeValue, 14)
    MAGNETOMETER_Y = typing___cast(ChannelTypeValue, 15)
    MAGNETOMETER_Z = typing___cast(ChannelTypeValue, 16)
    GYROSCOPE_X = typing___cast(ChannelTypeValue, 17)
    GYROSCOPE_Y = typing___cast(ChannelTypeValue, 18)
    GYROSCOPE_Z = typing___cast(ChannelTypeValue, 19)
    OTHER = typing___cast(ChannelTypeValue, 20)
    LIGHT = typing___cast(ChannelTypeValue, 21)
    IMAGE = typing___cast(ChannelTypeValue, 22)
    INFRARED = typing___cast(ChannelTypeValue, 23)
MICROPHONE = typing___cast(ChannelTypeValue, 0)
BAROMETER = typing___cast(ChannelTypeValue, 1)
LATITUDE = typing___cast(ChannelTypeValue, 2)
LONGITUDE = typing___cast(ChannelTypeValue, 3)
SPEED = typing___cast(ChannelTypeValue, 4)
ALTITUDE = typing___cast(ChannelTypeValue, 5)
RESERVED_0 = typing___cast(ChannelTypeValue, 6)
RESERVED_1 = typing___cast(ChannelTypeValue, 7)
RESERVED_2 = typing___cast(ChannelTypeValue, 8)
TIME_SYNCHRONIZATION = typing___cast(ChannelTypeValue, 9)
ACCURACY = typing___cast(ChannelTypeValue, 10)
ACCELEROMETER_X = typing___cast(ChannelTypeValue, 11)
ACCELEROMETER_Y = typing___cast(ChannelTypeValue, 12)
ACCELEROMETER_Z = typing___cast(ChannelTypeValue, 13)
MAGNETOMETER_X = typing___cast(ChannelTypeValue, 14)
MAGNETOMETER_Y = typing___cast(ChannelTypeValue, 15)
MAGNETOMETER_Z = typing___cast(ChannelTypeValue, 16)
GYROSCOPE_X = typing___cast(ChannelTypeValue, 17)
GYROSCOPE_Y = typing___cast(ChannelTypeValue, 18)
GYROSCOPE_Z = typing___cast(ChannelTypeValue, 19)
OTHER = typing___cast(ChannelTypeValue, 20)
LIGHT = typing___cast(ChannelTypeValue, 21)
IMAGE = typing___cast(ChannelTypeValue, 22)
INFRARED = typing___cast(ChannelTypeValue, 23)
type___ChannelType = ChannelType

class RedvoxPacket(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    api: builtin___int = ...
    uuid: typing___Text = ...
    redvox_id: typing___Text = ...
    authenticated_email: typing___Text = ...
    authentication_token: typing___Text = ...
    firebase_token: typing___Text = ...
    is_backfilled: builtin___bool = ...
    is_private: builtin___bool = ...
    is_scrambled: builtin___bool = ...
    device_make: typing___Text = ...
    device_model: typing___Text = ...
    device_os: typing___Text = ...
    device_os_version: typing___Text = ...
    app_version: typing___Text = ...
    battery_level_percent: builtin___float = ...
    device_temperature_c: builtin___float = ...
    acquisition_server: typing___Text = ...
    time_synchronization_server: typing___Text = ...
    authentication_server: typing___Text = ...
    app_file_start_timestamp_epoch_microseconds_utc: builtin___int = ...
    app_file_start_timestamp_machine: builtin___int = ...
    server_timestamp_epoch_microseconds_utc: builtin___int = ...
    metadata: google___protobuf___internal___containers___RepeatedScalarFieldContainer[typing___Text] = ...

    @property
    def evenly_sampled_channels(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___EvenlySampledChannel]: ...

    @property
    def unevenly_sampled_channels(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___UnevenlySampledChannel]: ...

    def __init__(self,
        *,
        api : typing___Optional[builtin___int] = None,
        uuid : typing___Optional[typing___Text] = None,
        redvox_id : typing___Optional[typing___Text] = None,
        authenticated_email : typing___Optional[typing___Text] = None,
        authentication_token : typing___Optional[typing___Text] = None,
        firebase_token : typing___Optional[typing___Text] = None,
        is_backfilled : typing___Optional[builtin___bool] = None,
        is_private : typing___Optional[builtin___bool] = None,
        is_scrambled : typing___Optional[builtin___bool] = None,
        device_make : typing___Optional[typing___Text] = None,
        device_model : typing___Optional[typing___Text] = None,
        device_os : typing___Optional[typing___Text] = None,
        device_os_version : typing___Optional[typing___Text] = None,
        app_version : typing___Optional[typing___Text] = None,
        battery_level_percent : typing___Optional[builtin___float] = None,
        device_temperature_c : typing___Optional[builtin___float] = None,
        acquisition_server : typing___Optional[typing___Text] = None,
        time_synchronization_server : typing___Optional[typing___Text] = None,
        authentication_server : typing___Optional[typing___Text] = None,
        app_file_start_timestamp_epoch_microseconds_utc : typing___Optional[builtin___int] = None,
        app_file_start_timestamp_machine : typing___Optional[builtin___int] = None,
        server_timestamp_epoch_microseconds_utc : typing___Optional[builtin___int] = None,
        evenly_sampled_channels : typing___Optional[typing___Iterable[type___EvenlySampledChannel]] = None,
        unevenly_sampled_channels : typing___Optional[typing___Iterable[type___UnevenlySampledChannel]] = None,
        metadata : typing___Optional[typing___Iterable[typing___Text]] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"acquisition_server",b"acquisition_server",u"api",b"api",u"app_file_start_timestamp_epoch_microseconds_utc",b"app_file_start_timestamp_epoch_microseconds_utc",u"app_file_start_timestamp_machine",b"app_file_start_timestamp_machine",u"app_version",b"app_version",u"authenticated_email",b"authenticated_email",u"authentication_server",b"authentication_server",u"authentication_token",b"authentication_token",u"battery_level_percent",b"battery_level_percent",u"device_make",b"device_make",u"device_model",b"device_model",u"device_os",b"device_os",u"device_os_version",b"device_os_version",u"device_temperature_c",b"device_temperature_c",u"evenly_sampled_channels",b"evenly_sampled_channels",u"firebase_token",b"firebase_token",u"is_backfilled",b"is_backfilled",u"is_private",b"is_private",u"is_scrambled",b"is_scrambled",u"metadata",b"metadata",u"redvox_id",b"redvox_id",u"server_timestamp_epoch_microseconds_utc",b"server_timestamp_epoch_microseconds_utc",u"time_synchronization_server",b"time_synchronization_server",u"unevenly_sampled_channels",b"unevenly_sampled_channels",u"uuid",b"uuid"]) -> None: ...
type___RedvoxPacket = RedvoxPacket

class Int32Payload(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    payload: google___protobuf___internal___containers___RepeatedScalarFieldContainer[builtin___int] = ...

    def __init__(self,
        *,
        payload : typing___Optional[typing___Iterable[builtin___int]] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"payload",b"payload"]) -> None: ...
type___Int32Payload = Int32Payload

class UInt32Payload(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    payload: google___protobuf___internal___containers___RepeatedScalarFieldContainer[builtin___int] = ...

    def __init__(self,
        *,
        payload : typing___Optional[typing___Iterable[builtin___int]] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"payload",b"payload"]) -> None: ...
type___UInt32Payload = UInt32Payload

class Int64Payload(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    payload: google___protobuf___internal___containers___RepeatedScalarFieldContainer[builtin___int] = ...

    def __init__(self,
        *,
        payload : typing___Optional[typing___Iterable[builtin___int]] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"payload",b"payload"]) -> None: ...
type___Int64Payload = Int64Payload

class UInt64Payload(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    payload: google___protobuf___internal___containers___RepeatedScalarFieldContainer[builtin___int] = ...

    def __init__(self,
        *,
        payload : typing___Optional[typing___Iterable[builtin___int]] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"payload",b"payload"]) -> None: ...
type___UInt64Payload = UInt64Payload

class Float32Payload(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    payload: google___protobuf___internal___containers___RepeatedScalarFieldContainer[builtin___float] = ...

    def __init__(self,
        *,
        payload : typing___Optional[typing___Iterable[builtin___float]] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"payload",b"payload"]) -> None: ...
type___Float32Payload = Float32Payload

class Float64Payload(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    payload: google___protobuf___internal___containers___RepeatedScalarFieldContainer[builtin___float] = ...

    def __init__(self,
        *,
        payload : typing___Optional[typing___Iterable[builtin___float]] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"payload",b"payload"]) -> None: ...
type___Float64Payload = Float64Payload

class BytePayload(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    BytePayloadTypeValue = typing___NewType('BytePayloadTypeValue', builtin___int)
    type___BytePayloadTypeValue = BytePayloadTypeValue
    BytePayloadType: _BytePayloadType
    class _BytePayloadType(google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper[BytePayload.BytePayloadTypeValue]):
        DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
        BYTES = typing___cast(BytePayload.BytePayloadTypeValue, 0)
        UINT8 = typing___cast(BytePayload.BytePayloadTypeValue, 1)
        UNINT16 = typing___cast(BytePayload.BytePayloadTypeValue, 2)
        UNINT24 = typing___cast(BytePayload.BytePayloadTypeValue, 3)
        UINT32 = typing___cast(BytePayload.BytePayloadTypeValue, 4)
        UINT64 = typing___cast(BytePayload.BytePayloadTypeValue, 5)
        INT8 = typing___cast(BytePayload.BytePayloadTypeValue, 6)
        INT16 = typing___cast(BytePayload.BytePayloadTypeValue, 7)
        INT24 = typing___cast(BytePayload.BytePayloadTypeValue, 8)
        INT32 = typing___cast(BytePayload.BytePayloadTypeValue, 9)
        INT64 = typing___cast(BytePayload.BytePayloadTypeValue, 10)
        FLOAT32 = typing___cast(BytePayload.BytePayloadTypeValue, 11)
        FLOAT64 = typing___cast(BytePayload.BytePayloadTypeValue, 12)
        OTHER = typing___cast(BytePayload.BytePayloadTypeValue, 13)
    BYTES = typing___cast(BytePayload.BytePayloadTypeValue, 0)
    UINT8 = typing___cast(BytePayload.BytePayloadTypeValue, 1)
    UNINT16 = typing___cast(BytePayload.BytePayloadTypeValue, 2)
    UNINT24 = typing___cast(BytePayload.BytePayloadTypeValue, 3)
    UINT32 = typing___cast(BytePayload.BytePayloadTypeValue, 4)
    UINT64 = typing___cast(BytePayload.BytePayloadTypeValue, 5)
    INT8 = typing___cast(BytePayload.BytePayloadTypeValue, 6)
    INT16 = typing___cast(BytePayload.BytePayloadTypeValue, 7)
    INT24 = typing___cast(BytePayload.BytePayloadTypeValue, 8)
    INT32 = typing___cast(BytePayload.BytePayloadTypeValue, 9)
    INT64 = typing___cast(BytePayload.BytePayloadTypeValue, 10)
    FLOAT32 = typing___cast(BytePayload.BytePayloadTypeValue, 11)
    FLOAT64 = typing___cast(BytePayload.BytePayloadTypeValue, 12)
    OTHER = typing___cast(BytePayload.BytePayloadTypeValue, 13)
    type___BytePayloadType = BytePayloadType

    bytePayloadType: type___BytePayload.BytePayloadTypeValue = ...
    payload: builtin___bytes = ...

    def __init__(self,
        *,
        bytePayloadType : typing___Optional[type___BytePayload.BytePayloadTypeValue] = None,
        payload : typing___Optional[builtin___bytes] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"bytePayloadType",b"bytePayloadType",u"payload",b"payload"]) -> None: ...
type___BytePayload = BytePayload

class EvenlySampledChannel(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    channel_types: google___protobuf___internal___containers___RepeatedScalarFieldContainer[type___ChannelTypeValue] = ...
    sensor_name: typing___Text = ...
    sample_rate_hz: builtin___float = ...
    first_sample_timestamp_epoch_microseconds_utc: builtin___int = ...
    value_means: google___protobuf___internal___containers___RepeatedScalarFieldContainer[builtin___float] = ...
    value_stds: google___protobuf___internal___containers___RepeatedScalarFieldContainer[builtin___float] = ...
    value_medians: google___protobuf___internal___containers___RepeatedScalarFieldContainer[builtin___float] = ...
    metadata: google___protobuf___internal___containers___RepeatedScalarFieldContainer[typing___Text] = ...

    @property
    def byte_payload(self) -> type___BytePayload: ...

    @property
    def uint32_payload(self) -> type___UInt32Payload: ...

    @property
    def uint64_payload(self) -> type___UInt64Payload: ...

    @property
    def int32_payload(self) -> type___Int32Payload: ...

    @property
    def int64_payload(self) -> type___Int64Payload: ...

    @property
    def float32_payload(self) -> type___Float32Payload: ...

    @property
    def float64_payload(self) -> type___Float64Payload: ...

    def __init__(self,
        *,
        channel_types : typing___Optional[typing___Iterable[type___ChannelTypeValue]] = None,
        sensor_name : typing___Optional[typing___Text] = None,
        sample_rate_hz : typing___Optional[builtin___float] = None,
        first_sample_timestamp_epoch_microseconds_utc : typing___Optional[builtin___int] = None,
        byte_payload : typing___Optional[type___BytePayload] = None,
        uint32_payload : typing___Optional[type___UInt32Payload] = None,
        uint64_payload : typing___Optional[type___UInt64Payload] = None,
        int32_payload : typing___Optional[type___Int32Payload] = None,
        int64_payload : typing___Optional[type___Int64Payload] = None,
        float32_payload : typing___Optional[type___Float32Payload] = None,
        float64_payload : typing___Optional[type___Float64Payload] = None,
        value_means : typing___Optional[typing___Iterable[builtin___float]] = None,
        value_stds : typing___Optional[typing___Iterable[builtin___float]] = None,
        value_medians : typing___Optional[typing___Iterable[builtin___float]] = None,
        metadata : typing___Optional[typing___Iterable[typing___Text]] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"byte_payload",b"byte_payload",u"float32_payload",b"float32_payload",u"float64_payload",b"float64_payload",u"int32_payload",b"int32_payload",u"int64_payload",b"int64_payload",u"payload",b"payload",u"uint32_payload",b"uint32_payload",u"uint64_payload",b"uint64_payload"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"byte_payload",b"byte_payload",u"channel_types",b"channel_types",u"first_sample_timestamp_epoch_microseconds_utc",b"first_sample_timestamp_epoch_microseconds_utc",u"float32_payload",b"float32_payload",u"float64_payload",b"float64_payload",u"int32_payload",b"int32_payload",u"int64_payload",b"int64_payload",u"metadata",b"metadata",u"payload",b"payload",u"sample_rate_hz",b"sample_rate_hz",u"sensor_name",b"sensor_name",u"uint32_payload",b"uint32_payload",u"uint64_payload",b"uint64_payload",u"value_means",b"value_means",u"value_medians",b"value_medians",u"value_stds",b"value_stds"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions___Literal[u"payload",b"payload"]) -> typing_extensions___Literal["byte_payload","uint32_payload","uint64_payload","int32_payload","int64_payload","float32_payload","float64_payload"]: ...
type___EvenlySampledChannel = EvenlySampledChannel

class UnevenlySampledChannel(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    channel_types: google___protobuf___internal___containers___RepeatedScalarFieldContainer[type___ChannelTypeValue] = ...
    sensor_name: typing___Text = ...
    timestamps_microseconds_utc: google___protobuf___internal___containers___RepeatedScalarFieldContainer[builtin___int] = ...
    sample_interval_mean: builtin___float = ...
    sample_interval_std: builtin___float = ...
    sample_interval_median: builtin___float = ...
    value_means: google___protobuf___internal___containers___RepeatedScalarFieldContainer[builtin___float] = ...
    value_stds: google___protobuf___internal___containers___RepeatedScalarFieldContainer[builtin___float] = ...
    value_medians: google___protobuf___internal___containers___RepeatedScalarFieldContainer[builtin___float] = ...
    metadata: google___protobuf___internal___containers___RepeatedScalarFieldContainer[typing___Text] = ...

    @property
    def byte_payload(self) -> type___BytePayload: ...

    @property
    def uint32_payload(self) -> type___UInt32Payload: ...

    @property
    def uint64_payload(self) -> type___UInt64Payload: ...

    @property
    def int32_payload(self) -> type___Int32Payload: ...

    @property
    def int64_payload(self) -> type___Int64Payload: ...

    @property
    def float32_payload(self) -> type___Float32Payload: ...

    @property
    def float64_payload(self) -> type___Float64Payload: ...

    def __init__(self,
        *,
        channel_types : typing___Optional[typing___Iterable[type___ChannelTypeValue]] = None,
        sensor_name : typing___Optional[typing___Text] = None,
        timestamps_microseconds_utc : typing___Optional[typing___Iterable[builtin___int]] = None,
        byte_payload : typing___Optional[type___BytePayload] = None,
        uint32_payload : typing___Optional[type___UInt32Payload] = None,
        uint64_payload : typing___Optional[type___UInt64Payload] = None,
        int32_payload : typing___Optional[type___Int32Payload] = None,
        int64_payload : typing___Optional[type___Int64Payload] = None,
        float32_payload : typing___Optional[type___Float32Payload] = None,
        float64_payload : typing___Optional[type___Float64Payload] = None,
        sample_interval_mean : typing___Optional[builtin___float] = None,
        sample_interval_std : typing___Optional[builtin___float] = None,
        sample_interval_median : typing___Optional[builtin___float] = None,
        value_means : typing___Optional[typing___Iterable[builtin___float]] = None,
        value_stds : typing___Optional[typing___Iterable[builtin___float]] = None,
        value_medians : typing___Optional[typing___Iterable[builtin___float]] = None,
        metadata : typing___Optional[typing___Iterable[typing___Text]] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"byte_payload",b"byte_payload",u"float32_payload",b"float32_payload",u"float64_payload",b"float64_payload",u"int32_payload",b"int32_payload",u"int64_payload",b"int64_payload",u"payload",b"payload",u"uint32_payload",b"uint32_payload",u"uint64_payload",b"uint64_payload"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"byte_payload",b"byte_payload",u"channel_types",b"channel_types",u"float32_payload",b"float32_payload",u"float64_payload",b"float64_payload",u"int32_payload",b"int32_payload",u"int64_payload",b"int64_payload",u"metadata",b"metadata",u"payload",b"payload",u"sample_interval_mean",b"sample_interval_mean",u"sample_interval_median",b"sample_interval_median",u"sample_interval_std",b"sample_interval_std",u"sensor_name",b"sensor_name",u"timestamps_microseconds_utc",b"timestamps_microseconds_utc",u"uint32_payload",b"uint32_payload",u"uint64_payload",b"uint64_payload",u"value_means",b"value_means",u"value_medians",b"value_medians",u"value_stds",b"value_stds"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions___Literal[u"payload",b"payload"]) -> typing_extensions___Literal["byte_payload","uint32_payload","uint64_payload","int32_payload","int64_payload","float32_payload","float64_payload"]: ...
type___UnevenlySampledChannel = UnevenlySampledChannel

class RedvoxPacketResponse(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    TypeValue = typing___NewType('TypeValue', builtin___int)
    type___TypeValue = TypeValue
    Type: _Type
    class _Type(google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper[RedvoxPacketResponse.TypeValue]):
        DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
        OK = typing___cast(RedvoxPacketResponse.TypeValue, 0)
        ERROR = typing___cast(RedvoxPacketResponse.TypeValue, 1)
    OK = typing___cast(RedvoxPacketResponse.TypeValue, 0)
    ERROR = typing___cast(RedvoxPacketResponse.TypeValue, 1)
    type___Type = Type

    ErrorValue = typing___NewType('ErrorValue', builtin___int)
    type___ErrorValue = ErrorValue
    Error: _Error
    class _Error(google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper[RedvoxPacketResponse.ErrorValue]):
        DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
        NOT_AUTHENTICATED = typing___cast(RedvoxPacketResponse.ErrorValue, 0)
        OTHER = typing___cast(RedvoxPacketResponse.ErrorValue, 1)
    NOT_AUTHENTICATED = typing___cast(RedvoxPacketResponse.ErrorValue, 0)
    OTHER = typing___cast(RedvoxPacketResponse.ErrorValue, 1)
    type___Error = Error

    type: type___RedvoxPacketResponse.TypeValue = ...
    checksum: builtin___int = ...
    errors: google___protobuf___internal___containers___RepeatedScalarFieldContainer[type___RedvoxPacketResponse.ErrorValue] = ...
    metadata: google___protobuf___internal___containers___RepeatedScalarFieldContainer[typing___Text] = ...

    def __init__(self,
        *,
        type : typing___Optional[type___RedvoxPacketResponse.TypeValue] = None,
        checksum : typing___Optional[builtin___int] = None,
        errors : typing___Optional[typing___Iterable[type___RedvoxPacketResponse.ErrorValue]] = None,
        metadata : typing___Optional[typing___Iterable[typing___Text]] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"checksum",b"checksum",u"errors",b"errors",u"metadata",b"metadata",u"type",b"type"]) -> None: ...
type___RedvoxPacketResponse = RedvoxPacketResponse
